---
title: "AOA-first300"
author: "Samah"
date: "2024-02-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
# remotes::install_github("langcog/wordbankr")
library(wordbankr)
library(jsonlite)

```

``` {r function for getting the first 300 words by AoA}

calculate_first300 <- function(chosenlanguage) {
  ws_data <- get_instrument_data(language = chosenlanguage,
                                     form = "WS",
                                     item_info = TRUE,
                                     administration_info = TRUE)
  
  ws_aoa <- fit_aoa(filter(ws_data, item_kind == "word"))
  
  first_300 <- ws_aoa |>
  filter(!is.na(aoa) & lexical_category == "nouns") |>
  arrange(aoa) |>
  slice(1:300) |> 
  mutate( language = chosenlanguage)
  
  return(first_300)
}

```

```{r}
languages <- c("English (American)", "Mandarin (Beijing)", "Korean", "English (Australian)", "Cantonese", "Catalan" , "Japanese", "Turkish" , "Spanish (Mexican)", "Russian", "Kiswahili", "Mandarin (Taiwanese)", "Spanish (Peruvian)", "Spanish (European)", "Hebrew", "French (French)")

# arabic, spanish chile, english uk , "Persian" , "Kigiriama", "Slovak", , "Spanish (Chilean)"

# Use purrr::map_df to apply the function and bind the results
allangs <- map_df(languages, ~ calculate_first300(chosenlanguage = .x))

words <- allangs %>% 
  select(uni_lemma, language) %>% 
  filter(!is.na(uni_lemma)) |>
  mutate(uni_lemma = str_to_lower(uni_lemma)) |>
  unique()

words |> filter( uni_lemma == "cracker")
toJSON(words)
write_csv(as.data.frame(words), "alllangs.csv")


```

``` {r}

#allnouns <- data.frame(unilemma = first_300$uni_lemma, language = first_300$lan)
#allnouns[nrow(allnouns)+1,] <- 
  
# eng_ws_data <- get_instrument_data(language = "English (American)",
#                                    form = "WS",
#                                    item_info = TRUE,
#                                    administration_info = TRUE)
# 
# eng_ws_aoa <- fit_aoa(filter(eng_ws_data, item_kind == "word"))
# 
# first_300 <- eng_ws_aoa |>
#   filter(!is.na(aoa)) |>
#   arrange(aoa) |>
#   slice(1:300) |> 
#   mutate( language = "English")


```
